#Removed from 1.13
#kubectl autoscale -n kubeguide rc hpa-example --min=1 --max=10 --cpu-percent=80
#kubectl -n kubeguide get hpa
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hpa-example
  namespace: kubeguide
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hpa-example
    spec:
      containers:
        - name: hpa-example
          image: busybox
          command: ["sh", "-c", "while :;  do sleep 1; done"]
          resources:
            requests:
              cpu: 0.05
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-example
spec:
  ports:
    - port: 80
  selector:
    app: hpa-example
