---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  require:
  - rubocop-i18n
  - rubocop-rspec
".travis.yml":
  dist: trusty
  deploy_to_forge:
    enabled: false
  user: puppet
  secure: ''
  branches:
  - release
  includes:
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=deb_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    stage: acceptance
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORM=centos:deb_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=ub_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_ub]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    stage: acceptance
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORM=centos:ub_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_ub]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el6_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el6]'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORM=centos:el6_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el6]'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    stage: acceptance
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el7_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el7]'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORM=centos:el7_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el7]'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    stage: acceptance
    sudo: required
  simplecov: true
  notifications:
    slack:
      secure: f7XbE9eVRGVVLoq1BYsib9T+elBhFoAs/Vojg1OaxFAixZSMAbHq+6egsAZuToSXwwo2XIYeBYbnyomvoKDrMw1UDQ93vc85AwZBvk4pKsPpF+jfgX+az56pu7LeZmEcDk+eWvvH2PPhOJmJpYcWR/gRKQciGSGHBiMgD8UmenU=
appveyor.yml:
  simplecov: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
  required:
    ":development":
    - gem: puppet-lint-i18n
Rakefile:
  requires:
  - puppet_pot_generator/rake_tasks
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
